version: "3.8"
#docker compose sirve para que los servicios se puedan comunicar entre si
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/lostpaws
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
